"""
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import time
t1 = time.time()
def asal_mi(sayı):
    if (sayı == 1):
        return False

    elif (sayı == 2):
        return True

    else:
        for i in range(2,sayı):
            if (sayı % i == 0):
                return False
        return True

kaça_kadar = 500
say = 1
while True:
    print(say)
    topla = int((say*(say+1))/2)
    cevap = topla
    üs = []
    for i in range(1,int(topla**0.5)):
        say2 = 0
        while i <= topla  and  topla%i == 0 and asal_mi(i):
            topla /= i
            say2 += 1
            
        üs.append(say2)

    çarp = 1
    for j in üs:
        çarp *= (j+1)

    if çarp > kaça_kadar:
        print("cevap: ", cevap)
        break
    else:
        say += 1

t2 = time.time()
print("Program Süresi: ", round(t2-t1,3))